/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  ": typeof types.ActionFragmentFragmentDoc,
    "\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  ": typeof types.ActivityFragmentFragmentDoc,
    "\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  ": typeof types.CampaignFragmentBaseFragmentDoc,
    "\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  ": typeof types.FactoryFragmentFragmentDoc,
    "\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  ": typeof types.TrancheFragmentFragmentDoc,
    "\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(limit: 1000) {\n      ...TrancheFragment\n    }\n  }\n": typeof types.CampaignFragmentFragmentDoc,
    "\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n": typeof types.AssetFragmentFragmentDoc,
    "\n  query getActions($first: Int!, $orderDirection: order_by!, $where: Action_bool_exp) {\n    actions: Action(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n": typeof types.GetActionsDocument,
    "\n  query getCampaign($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n": typeof types.GetCampaignDocument,
    "\n  query getCampaignMetadata(\n    $campaignId: String!\n    $campaignId_string: String!\n    $dayFrom: numeric!\n    $dayTo: numeric!\n  ) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      id\n      actions(\n        limit: 5\n        order_by: { subgraphId: desc }\n      ) {\n        ...ActionFragment\n      }\n      activities(\n        limit: 7\n        distinct_on: [day]\n        order_by: { day: asc }\n        where: {\n          day: { _gte: $dayFrom, _lte: $dayTo },\n          campaign_id: { _eq: $campaignId }\n        }\n      ) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: Action(\n      limit: 1\n      order_by: { subgraphId: asc, timestamp: asc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n    actions: Action(\n      limit: 10\n      order_by: { subgraphId: desc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n  }\n": typeof types.GetCampaignMetadataDocument,
    "\n  query getCampaignWithActions($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n": typeof types.GetCampaignWithActionsDocument,
    "\n  query getCampaigns($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n": typeof types.GetCampaignsDocument,
    "\n  query getCampaignsWithActions($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithActionsDocument,
    "\n  query getCampaignsWithActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      activities(limit: 1000, order_by: { timestamp: desc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithActivitiesDocument,
    "\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n      activities(limit: 1000, order_by: { timestamp: asc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithActionsAndActivitiesDocument,
    "\n  query getCampaignsWithClaims(\n    $claimer: String!\n    $first: Int!\n    $orderDirection: order_by!\n    $where: Campaign_bool_exp\n  ) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(\n        where: {\n          claimRecipient: { _eq: $claimer }\n          category: { _eq: \"Claim\" }\n        }\n      ) {\n        ...ActionFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithClaimsDocument,
};
const documents: Documents = {
    "\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  ": types.ActionFragmentFragmentDoc,
    "\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  ": types.ActivityFragmentFragmentDoc,
    "\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  ": types.CampaignFragmentBaseFragmentDoc,
    "\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  ": types.FactoryFragmentFragmentDoc,
    "\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  ": types.TrancheFragmentFragmentDoc,
    "\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(limit: 1000) {\n      ...TrancheFragment\n    }\n  }\n": types.CampaignFragmentFragmentDoc,
    "\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n": types.AssetFragmentFragmentDoc,
    "\n  query getActions($first: Int!, $orderDirection: order_by!, $where: Action_bool_exp) {\n    actions: Action(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n": types.GetActionsDocument,
    "\n  query getCampaign($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n": types.GetCampaignDocument,
    "\n  query getCampaignMetadata(\n    $campaignId: String!\n    $campaignId_string: String!\n    $dayFrom: numeric!\n    $dayTo: numeric!\n  ) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      id\n      actions(\n        limit: 5\n        order_by: { subgraphId: desc }\n      ) {\n        ...ActionFragment\n      }\n      activities(\n        limit: 7\n        distinct_on: [day]\n        order_by: { day: asc }\n        where: {\n          day: { _gte: $dayFrom, _lte: $dayTo },\n          campaign_id: { _eq: $campaignId }\n        }\n      ) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: Action(\n      limit: 1\n      order_by: { subgraphId: asc, timestamp: asc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n    actions: Action(\n      limit: 10\n      order_by: { subgraphId: desc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n  }\n": types.GetCampaignMetadataDocument,
    "\n  query getCampaignWithActions($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n": types.GetCampaignWithActionsDocument,
    "\n  query getCampaigns($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n": types.GetCampaignsDocument,
    "\n  query getCampaignsWithActions($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n": types.GetCampaignsWithActionsDocument,
    "\n  query getCampaignsWithActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      activities(limit: 1000, order_by: { timestamp: desc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n": types.GetCampaignsWithActivitiesDocument,
    "\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n      activities(limit: 1000, order_by: { timestamp: asc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n": types.GetCampaignsWithActionsAndActivitiesDocument,
    "\n  query getCampaignsWithClaims(\n    $claimer: String!\n    $first: Int!\n    $orderDirection: order_by!\n    $where: Campaign_bool_exp\n  ) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(\n        where: {\n          claimRecipient: { _eq: $claimer }\n          category: { _eq: \"Claim\" }\n        }\n      ) {\n        ...ActionFragment\n      }\n    }\n  }\n": types.GetCampaignsWithClaimsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  "): (typeof documents)["\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  "): (typeof documents)["\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  "): (typeof documents)["\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  "): (typeof documents)["\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  "): (typeof documents)["\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(limit: 1000) {\n      ...TrancheFragment\n    }\n  }\n"): (typeof documents)["\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(limit: 1000) {\n      ...TrancheFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n"): (typeof documents)["\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getActions($first: Int!, $orderDirection: order_by!, $where: Action_bool_exp) {\n    actions: Action(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getActions($first: Int!, $orderDirection: order_by!, $where: Action_bool_exp) {\n    actions: Action(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaign($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n"): (typeof documents)["\n  query getCampaign($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignMetadata(\n    $campaignId: String!\n    $campaignId_string: String!\n    $dayFrom: numeric!\n    $dayTo: numeric!\n  ) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      id\n      actions(\n        limit: 5\n        order_by: { subgraphId: desc }\n      ) {\n        ...ActionFragment\n      }\n      activities(\n        limit: 7\n        distinct_on: [day]\n        order_by: { day: asc }\n        where: {\n          day: { _gte: $dayFrom, _lte: $dayTo },\n          campaign_id: { _eq: $campaignId }\n        }\n      ) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: Action(\n      limit: 1\n      order_by: { subgraphId: asc, timestamp: asc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n    actions: Action(\n      limit: 10\n      order_by: { subgraphId: desc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n  }\n"): (typeof documents)["\n  query getCampaignMetadata(\n    $campaignId: String!\n    $campaignId_string: String!\n    $dayFrom: numeric!\n    $dayTo: numeric!\n  ) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      id\n      actions(\n        limit: 5\n        order_by: { subgraphId: desc }\n      ) {\n        ...ActionFragment\n      }\n      activities(\n        limit: 7\n        distinct_on: [day]\n        order_by: { day: asc }\n        where: {\n          day: { _gte: $dayFrom, _lte: $dayTo },\n          campaign_id: { _eq: $campaignId }\n        }\n      ) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: Action(\n      limit: 1\n      order_by: { subgraphId: asc, timestamp: asc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n    actions: Action(\n      limit: 10\n      order_by: { subgraphId: desc }\n      where: {\n        campaign_id: { _eq: $campaignId_string }\n        category: { _eq: \"Claim\" }\n      }\n    ) {\n      ...ActionFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignWithActions($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignWithActions($campaignId: String!) {\n    campaign: Campaign_by_pk(id: $campaignId) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaigns($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n"): (typeof documents)["\n  query getCampaigns($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithActions($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithActions($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      activities(limit: 1000, order_by: { timestamp: desc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      activities(limit: 1000, order_by: { timestamp: desc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n      activities(limit: 1000, order_by: { timestamp: asc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: order_by!, $where: Campaign_bool_exp) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(limit: 1000, order_by: { subgraphId: asc }) {\n        ...ActionFragment\n      }\n      activities(limit: 1000, order_by: { timestamp: asc }) {\n        ...ActivityFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithClaims(\n    $claimer: String!\n    $first: Int!\n    $orderDirection: order_by!\n    $where: Campaign_bool_exp\n  ) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(\n        where: {\n          claimRecipient: { _eq: $claimer }\n          category: { _eq: \"Claim\" }\n        }\n      ) {\n        ...ActionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithClaims(\n    $claimer: String!\n    $first: Int!\n    $orderDirection: order_by!\n    $where: Campaign_bool_exp\n  ) {\n    campaigns: Campaign(\n      limit: $first\n      order_by: { subgraphId: $orderDirection }\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(\n        where: {\n          claimRecipient: { _eq: $claimer }\n          category: { _eq: \"Claim\" }\n        }\n      ) {\n        ...ActionFragment\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;