# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  # Generate a summary of the changed files in the walkthrough.
  changed_files_summary: false

  # Collapse the walkthrough into a single comment.
  collapse_walkthrough: true

  # Set the profile for reviews. Assertive profile yields more feedback, that may be considered nitpicky.
  # Options: chill, assertive
  profile: "chill"

  # Generate a high level summary of the changes in the PR/MR description.
  high_level_summary: false

  # Generate a poem in the walkthrough comment.
  poem: false

  # Post review details on each review. Additionally, post a review status when a review is skipped in certain cases.
  review_status: false

  # Configuration for auto review
  auto_review:
    # Review draft PRs/MRs.
    drafts: false

    # Automatic Review - Automatic code review
    # Setting it to false will require tagging the PR with @coderabbitai to trigger a review.
    enabled: true

  # Configuration for pre merge checks
  pre_merge_checks:
    # Docstring Coverage - Checks if the code has sufficient docstrings.
    docstrings:
      # Mode - Determines how strictly the docstring coverage check is enforced. Warning will only generate a warning
      # and does not require the user to resolve the check. Error requires the user to resolve issues before merging the
      # pull request.
      # Options: off, warning, error
      mode: "off"
