extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  project: ["**/tsconfig.json"]
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/ban-ts-comment": "off"
  "@typescript-eslint/ban-ts-ignore": "off"
  "@typescript-eslint/ban-types": "off"
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/no-explicit-any": "error"
  "@typescript-eslint/no-floating-promises":
    - error
    - ignoreIIFE: true
      ignoreVoid: true
  "@typescript-eslint/no-non-null-assertion": "off"
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "_"
      varsIgnorePattern: "_"
  curly:
    - error
    - all
  no-constant-condition: "off"
  no-empty-pattern: "off"
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  prefer-const: "off"
