endOfLine: "auto"
plugins:
  - "@trivago/prettier-plugin-sort-imports"
printWidth: 80
trailingComma: "all"

overrides:
  - files: "*.md"
    options:
      printWidth: 120
      proseWrap: "always"
  - files: ["*.d.ts", "*.ts", "*.tsx"]
    options:
      importOrder:
        - "^@"
        - "<TS_TYPES>"
        - "<THIRD_PARTY_MODULES>"
        - "<THIRD_PARTY_TS_TYPES>"
        - "^../generated|^../../src/generated"
        - "^[./]"
      importOrderSeparation: false
      importOrderSortSpecifiers: true
  - files: ["*.yml", "*.yaml", "*.graphql"]
    options:
      bracketSpacing: false
      printWidth: 120
