# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-merkle
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
    - "value"
contracts:
  - name: MerkleLockupFactoryV21
    handler: src/mappings/index.ts
    events:
      - event:
          CreateMerkleStreamerLL(address merkleStreamer, address indexed admin, address indexed lockupLinear, address
          indexed asset, bytes32 merkleRoot, uint40 expiration, (uint40, uint40) streamDurations, bool cancelable, bool
          transferable, string ipfsCID, uint256 aggregateAmount, uint256 recipientsCount)
  - name: MerkleLockupFactoryV22
    handler: src/mappings/index.ts
    events:
      - event: CreateMerkleLL(address indexed merkleLL, (address, bool, uint40, address, string, bytes32, string, bool) baseParams, address lockupLinear, (uint40, uint40) streamDurations, uint256 aggregateAmount, uint256 recipientCount)
      - event: CreateMerkleLT(address indexed merkleLT, (address, bool, uint40, address, string, bytes32, string, bool) baseParams, address lockupTranched, (uint64, uint40)[] tranchesWithPercentages, uint256 totalDuration, uint256 aggregateAmount,uint256 recipientCount)
  - name: MerkleLockupFactoryV23
    handler: src/mappings/index.ts
    events:
      - event: CreateMerkleLL(address indexed merkleLL, (address, uint40, address, string, bytes32, string, string) baseParams, address lockup, bool cancelable, bool transferable, (uint40, uint64, uint40, uint64, uint40) schedule, uint256 aggregateAmount, uint256 recipientCount, uint256 fee)
      - event: CreateMerkleLT(address indexed merkleLT, (address, uint40, address, string, bytes32, string, string) baseParams, address lockup, bool cancelable, bool transferable, uint40 streamStartTime, (uint64, uint40)[] tranchesWithPercentages, uint256 totalDuration, uint256 aggregateAmount,uint256 recipientCount, uint256 fee)
      - event: CreateMerkleInstant(address indexed merkleInstant, (address, uint40, address, string, bytes32, string, string) baseParams, uint256 aggregateAmount, uint256 recipientCount, uint256 fee)
  - name: MerkleLockupV21
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
  - name: MerkleLockupV22
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
  - name: MerkleLockupV23
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount, uint256 indexed streamId)
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
  - name: MerkleInstant
    handler: src/mappings/index.ts
    events:
      - event: Claim(uint256 index, address indexed recipient, uint128 amount)
      - event: Clawback(address indexed admin, address indexed to, uint128 amount)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
networks:
  - id: 42161
    start_block: 161026550
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x237400ef5a41886a75b0e036228221df075b3b80
      - name: MerkleLockupFactoryV22
        address:
          - 0xc9a5a0bc2d8e217bdbdfe7486e9e72c5c3308f01
      - name: MerkleLockupFactoryV23
        address:
          - 0x7efd170e3e32dc1b4c17eb4cfff92c81ff43a6cb
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 43114
    start_block: 41023950
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x4849e797d7aab20fcc8f807efafdfff98a83412e
      - name: MerkleLockupFactoryV22
        address:
          - 0x0430ed39ea2789acdf27b89268117ebabc8176d1
      - name: MerkleLockupFactoryV23
        address:
          - 0x6bcd2260825cfed440bb765f7a92f6cdbdc90f43
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 8453
    start_block: 8026890
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x5545c8e7c3e1f74adc98e518f2e8d23a002c4412
      - name: MerkleLockupFactoryV22
        address:
          - 0x58a51e5382318eea6065bb7721eecdf4331c0b90
      - name: MerkleLockupFactoryV23
        address:
          - 0xd9e108f26fe104ce1058d48070438dedb3ad826a
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 84532
    start_block: 12641000
    contracts:
      - name: MerkleLockupFactoryV22
        address:
          - 0x899a05feb160fe912f621733a1d0b39c1446b3eb
      - name: MerkleLockupFactoryV23
        address:
          - 0x6a3466398a66c7ce801989b45c390cdc8717102d
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 81457
    start_block: 244700
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x92fc05e49c27884d554d98a5c01ff0894a9dc29a
      - name: MerkleLockupFactoryV22
        address:
          - 0x3abcdda756d069cf3c7a17410602343966eaff27
      - name: MerkleLockupFactoryV23
        address:
          - 0xdd40b4f5b216f524a55e2e8f75637e8b453e4bd2
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 56
    start_block: 34438430
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x434d73465aac4125d204a6637eb6c579d8d69f48
      - name: MerkleLockupFactoryV22
        address:
          - 0x96aa12809cac29bba4944feca1dfdc8e1704e6c1
      - name: MerkleLockupFactoryV23
        address:
          - 0xf9f89d99fb702b06fba16a294b7614089defe068
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 100
    start_block: 31491790
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x777f66477ff83ababadf39a3f22a8cc3aee43765
      - name: MerkleLockupFactoryV22
        address:
          - 0x5f12318fc6cca518a950e2ee16063a6317c2a9ef
      - name: MerkleLockupFactoryV23
        address:
          - 0x64ba580946985b4b87f4d9f7b6598c2156026775
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 59144
    start_block: 7728000
    contracts:
      - name: MerkleLockupFactoryV22
        address:
          - 0x35e9c3445a039b258eb7112a5eea259a825e8ac0
      - name: MerkleLockupFactoryV23
        address:
          - 0xaa122611e0e3a0771127aa4cd4995a896bb2c20b
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 1
    start_block: 17615650
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x1a272b596b10f02931480bc7a3617db4a8d154e3
      - name: MerkleLockupFactoryV22
        address:
          - 0xf35ab407cf28012ba57caf5ee2f6d6e4420253bc
      - name: MerkleLockupFactoryV23
        address:
          - 0x71dd3ca88e7564416e5c2e350090c12bf8f6144a
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 34443
    start_block: 11343000
    hypersync_config:
      url: https://mode.hypersync.xyz
    contracts:
      - name: MerkleLockupFactoryV22
        address:
          - 0x0fd01dd30f96a15de6afad5627d45ef94752460a
      - name: MerkleLockupFactoryV23
        address:
          - 0xc472391db89e7be07170f18c4fdb010242507f2c
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 2818
    start_block: 45000
    hypersync_config:
      url: https://morph.hypersync.xyz/
    contracts:
      - name: MerkleLockupFactoryV22
        address:
          - 0x5e73bb96493c10919204045fcdb639d35ad859f8
      - name: MerkleLockupFactoryV23
        address:
          - 0xbe64e8718d82c598ebcda5149d10eb68b79632a4
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 10
    start_block: 113621900
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x044ec80fbec40f0ee7e7b3856828170971796c19
      - name: MerkleLockupFactoryV22
        address:
          - 0xe041629d99730b3ee4d6518097c45b4e3591992b
      - name: MerkleLockupFactoryV23
        address:
          - 0x2455bff7a71e6e441b2d0b1b1e480fe36ebf6d1e
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 137
    start_block: 51245830
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xf4906225e783fb8977410bdbfb960cabed6c2ef4
      - name: MerkleLockupFactoryV22
        address:
          - 0xc28872e0c1f3633eed467907123727ac0155029d
      - name: MerkleLockupFactoryV23
        address:
          - 0xf0d61b42311c810dfde191d58427d81e87c5d5f6
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 534352
    start_block: 1675330
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xb3ade5463000e6c0d376e7d7570f372ebf98bdaf
      - name: MerkleLockupFactoryV22
        address:
          - 0x344afe8ad5dba3d55870dc398e0f53b635b2ed0d
      - name: MerkleLockupFactoryV23
        address:
          - 0x6df0bffdb106b19d1e954853f4d14003e21b7854
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0xbacc1d151a78eed71d504f701c25e8739dc0262d
      - name: MerkleLockupFactoryV22
        address:
          - 0x56e9180a8d2c35c99f2f8a1a5ab8abe79e876e8c
      - name: MerkleLockupFactoryV23
        address:
          - 0xf642751d1271c88bbb8786067de808b32a016fd4
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 5330
    start_block: 2896400
    hypersync_config:
      url: https://extrabud.hypersync.xyz
    contracts:
      - name: MerkleLockupFactoryV22
        address:
          - 0xf60beadefbeb98c927e13c4165bca7d85ba32cb2
      - name: MerkleLockupFactoryV23
        address:
          - 0x3df48bb93509d9a041c81f6670c37b1eeb3e154b
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 5845
    start_block: 2516000
    hypersync_config:
      url: https://tangle.hypersync.xyz
    contracts:
      - name: MerkleLockupFactoryV22
        address:
          - 0x5e73bb96493c10919204045fcdb639d35ad859f8
      - name: MerkleLockupFactoryV23
        address:
          - 0xd641a0e4509cced67cc24e7bdcde2a31b7f7cf77
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
  - id: 324
    start_block: 33148900
    contracts:
      - name: MerkleLockupFactoryV21
        address:
          - 0x46de683d20c3575a0381ffd66c10ab6836390140
      - name: MerkleLockupFactoryV22
        address:
          - 0x8a84fcf962163a7e98bf0dafd918973c846fa5c8
      - name: MerkleLockupFactoryV23
        address:
          - 0x8e7e78799f8cc87d4816112a758281dabc158452
      - name: MerkleLockupV21
      - name: MerkleLockupV22
      - name: MerkleLockupV23
      - name: MerkleInstant
