import "../envio.just"

export ENVIO_HASURA_PUBLIC_AGGREGATE := "Action&Asset&Batch&Stream"
export ENVIO_INDEXER_NAME := "flow"
export INDEXER_NAME := "flow"

# Show available commands
default:
    @just --list
