import "../envio.just"

# Run `just --evaluate ENVIO_HASURA_PUBLIC_AGGREGATE` to see the result
export ENVIO_HASURA_PUBLIC_AGGREGATE := ```
    arr=(
        "Action"
        "Asset"
        "Batch"
        "Stream"
    )
    IFS='&' # Internal Field Separator
    echo "${arr[*]}"
```
export ENVIO_INDEXER_NAME := "flow"
export INDEXER_NAME := "flow"

# Show available commands
default:
    @just --list
