import "../envio.just"

# Run `just --evaluate ENVIO_HASURA_PUBLIC_AGGREGATE` to see the result
export ENVIO_HASURA_PUBLIC_AGGREGATE := "Asset&FlowAction&FlowBatch&FlowStream&LockupAction&LockupBatch&LockupStream&Sponsor&Sponsorship"
export ENVIO_INDEXER_NAME := "streams"
export INDEXER_NAME := "streams"

# Show available commands
default:
    @just --list
