/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  ": typeof types.ActionFragmentFragmentDoc,
    "\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  ": typeof types.ActivityFragmentFragmentDoc,
    "\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  ": typeof types.CampaignFragmentBaseFragmentDoc,
    "\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  ": typeof types.FactoryFragmentFragmentDoc,
    "\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  ": typeof types.TrancheFragmentFragmentDoc,
    "\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(first: 1000, orderBy: position, orderDirection: asc) {\n      ...TrancheFragment\n    }\n  }\n": typeof types.CampaignFragmentFragmentDoc,
    "\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n": typeof types.AssetFragmentFragmentDoc,
    "\n  query getActions($first: Int!, $where: Action_filter) {\n    actions(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: desc\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n": typeof types.GetActionsDocument,
    "\n  query getCampaign($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n": typeof types.GetCampaignDocument,
    "\n  query getCampaignWithActions($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n": typeof types.GetCampaignWithActionsDocument,
    "\n  query getCampaignMetadata(\n    $campaignId: ID!\n    $campaignId_string: String!\n    $dayFrom: BigInt!\n    $dayTo: BigInt!\n  ) {\n    campaign(id: $campaignId) {\n      id\n      actions(first: 5, orderBy: subgraphId, orderDirection: desc) {\n        ...ActionFragment\n      }\n      activities(first: 7, where: { day_gte: $dayFrom, day_lte: $dayTo }) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: actions(\n      first: 1\n      orderBy: timestamp\n      orderDirection: asc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n    actions(\n      first: 10\n      orderBy: subgraphId\n      orderDirection: desc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n  }\n": typeof types.GetCampaignMetadataDocument,
    "\n  query getCampaigns($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n": typeof types.GetCampaignsDocument,
    "\n  query getCampaignsWithActions($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithActionsDocument,
    "\n  query getCampaignsWithActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithActivitiesDocument,
    "\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithActionsAndActivitiesDocument,
    "\n  query getCampaignsWithClaims(\n    $first: Int!\n    $claimer: Bytes!\n    $orderDirection: OrderDirection!\n    $where: Campaign_filter\n  ) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(where: { category: Claim, claimRecipient: $claimer }) {\n        ...ActionFragment\n      }\n    }\n  }\n": typeof types.GetCampaignsWithClaimsDocument,
};
const documents: Documents = {
    "\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  ": types.ActionFragmentFragmentDoc,
    "\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  ": types.ActivityFragmentFragmentDoc,
    "\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  ": types.CampaignFragmentBaseFragmentDoc,
    "\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  ": types.FactoryFragmentFragmentDoc,
    "\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  ": types.TrancheFragmentFragmentDoc,
    "\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(first: 1000, orderBy: position, orderDirection: asc) {\n      ...TrancheFragment\n    }\n  }\n": types.CampaignFragmentFragmentDoc,
    "\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n": types.AssetFragmentFragmentDoc,
    "\n  query getActions($first: Int!, $where: Action_filter) {\n    actions(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: desc\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n": types.GetActionsDocument,
    "\n  query getCampaign($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n": types.GetCampaignDocument,
    "\n  query getCampaignWithActions($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n": types.GetCampaignWithActionsDocument,
    "\n  query getCampaignMetadata(\n    $campaignId: ID!\n    $campaignId_string: String!\n    $dayFrom: BigInt!\n    $dayTo: BigInt!\n  ) {\n    campaign(id: $campaignId) {\n      id\n      actions(first: 5, orderBy: subgraphId, orderDirection: desc) {\n        ...ActionFragment\n      }\n      activities(first: 7, where: { day_gte: $dayFrom, day_lte: $dayTo }) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: actions(\n      first: 1\n      orderBy: timestamp\n      orderDirection: asc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n    actions(\n      first: 10\n      orderBy: subgraphId\n      orderDirection: desc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n  }\n": types.GetCampaignMetadataDocument,
    "\n  query getCampaigns($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n": types.GetCampaignsDocument,
    "\n  query getCampaignsWithActions($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n": types.GetCampaignsWithActionsDocument,
    "\n  query getCampaignsWithActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n": types.GetCampaignsWithActivitiesDocument,
    "\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n": types.GetCampaignsWithActionsAndActivitiesDocument,
    "\n  query getCampaignsWithClaims(\n    $first: Int!\n    $claimer: Bytes!\n    $orderDirection: OrderDirection!\n    $where: Campaign_filter\n  ) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(where: { category: Claim, claimRecipient: $claimer }) {\n        ...ActionFragment\n      }\n    }\n  }\n": types.GetCampaignsWithClaimsDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  "): (typeof documents)["\n    fragment ActionFragment on Action {\n      id\n      block\n      category\n      chainId\n      claimAmount\n      claimIndex\n      claimRecipient\n      claimStreamId\n      claimTokenId\n      clawbackAmount\n      clawbackFrom\n      clawbackTo\n      fee\n      from\n      hash\n      subgraphId\n      timestamp\n      campaign {\n        id\n        name\n        nickname\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  "): (typeof documents)["\n    fragment ActivityFragment on Activity {\n      id\n      amount\n      claims\n      day\n      timestamp\n      campaign {\n        id\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  "): (typeof documents)["\n    fragment CampaignFragmentBase on Campaign {\n      id\n      address\n      admin\n      aggregateAmount\n      category\n      chainId\n      claimedAmount\n      claimedCount\n      clawbackTime\n      expiration\n      expires\n      fee\n      hash\n      ipfsCID\n      lockup\n      name\n      nickname\n      root\n      streamCancelable\n      streamCliff\n      streamCliffDuration\n      streamCliffPercentage\n      streamInitial\n      streamInitialPercentage\n      streamShape\n      streamStart\n      streamStartTime\n      streamTotalDuration\n      streamTransferable\n      subgraphId\n      timestamp\n      totalRecipients\n      version\n      asset {\n        ...AssetFragment\n      }\n      factory {\n        ...FactoryFragment\n      }\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  "): (typeof documents)["\n    fragment FactoryFragment on Factory {\n      id\n      address\n      alias\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  "): (typeof documents)["\n    fragment TrancheFragment on Tranche {\n      id\n      duration\n      endDuration\n      endPercentage\n      percentage\n      position\n      startDuration\n      startPercentage\n    }\n  "];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(first: 1000, orderBy: position, orderDirection: asc) {\n      ...TrancheFragment\n    }\n  }\n"): (typeof documents)["\n  fragment CampaignFragment on Campaign {\n    ...CampaignFragmentBase\n    streamTranches(first: 1000, orderBy: position, orderDirection: asc) {\n      ...TrancheFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n"): (typeof documents)["\n  fragment AssetFragment on Asset {\n    id\n    address\n    chainId\n    decimals\n    name\n    symbol\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getActions($first: Int!, $where: Action_filter) {\n    actions(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: desc\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query getActions($first: Int!, $where: Action_filter) {\n    actions(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: desc\n      where: $where\n    ) {\n      ...ActionFragment\n      campaign {\n        id\n        category\n        name\n        nickname\n        asset {\n          ...AssetFragment\n        }\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaign($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n"): (typeof documents)["\n  query getCampaign($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignWithActions($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignWithActions($campaignId: ID!) {\n    campaign(id: $campaignId) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignMetadata(\n    $campaignId: ID!\n    $campaignId_string: String!\n    $dayFrom: BigInt!\n    $dayTo: BigInt!\n  ) {\n    campaign(id: $campaignId) {\n      id\n      actions(first: 5, orderBy: subgraphId, orderDirection: desc) {\n        ...ActionFragment\n      }\n      activities(first: 7, where: { day_gte: $dayFrom, day_lte: $dayTo }) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: actions(\n      first: 1\n      orderBy: timestamp\n      orderDirection: asc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n    actions(\n      first: 10\n      orderBy: subgraphId\n      orderDirection: desc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n  }\n"): (typeof documents)["\n  query getCampaignMetadata(\n    $campaignId: ID!\n    $campaignId_string: String!\n    $dayFrom: BigInt!\n    $dayTo: BigInt!\n  ) {\n    campaign(id: $campaignId) {\n      id\n      actions(first: 5, orderBy: subgraphId, orderDirection: desc) {\n        ...ActionFragment\n      }\n      activities(first: 7, where: { day_gte: $dayFrom, day_lte: $dayTo }) {\n        ...ActivityFragment\n      }\n      asset {\n        ...AssetFragment\n      }\n    }\n    firsts: actions(\n      first: 1\n      orderBy: timestamp\n      orderDirection: asc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n    actions(\n      first: 10\n      orderBy: subgraphId\n      orderDirection: desc\n      where: { campaign: $campaignId_string, category: Claim }\n    ) {\n      ...ActionFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaigns($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n"): (typeof documents)["\n  query getCampaigns($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithActions($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithActions($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithActionsAndActivities($first: Int!, $orderDirection: OrderDirection!, $where: Campaign_filter) {\n    campaigns(first: $first, orderBy: subgraphId, orderDirection: $orderDirection, where: $where) {\n      ...CampaignFragment\n      actions(first: 1000, orderBy: subgraphId, orderDirection: asc) {\n        ...ActionFragment\n      }\n      activities(first: 1000, orderBy: timestamp, orderDirection: asc) {\n        ...ActivityFragment\n      }\n    }\n  }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n  query getCampaignsWithClaims(\n    $first: Int!\n    $claimer: Bytes!\n    $orderDirection: OrderDirection!\n    $where: Campaign_filter\n  ) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(where: { category: Claim, claimRecipient: $claimer }) {\n        ...ActionFragment\n      }\n    }\n  }\n"): (typeof documents)["\n  query getCampaignsWithClaims(\n    $first: Int!\n    $claimer: Bytes!\n    $orderDirection: OrderDirection!\n    $where: Campaign_filter\n  ) {\n    campaigns(\n      first: $first\n      orderBy: subgraphId\n      orderDirection: $orderDirection\n      where: $where\n    ) {\n      ...CampaignFragment\n      actions(where: { category: Claim, claimRecipient: $claimer }) {\n        ...ActionFragment\n      }\n    }\n  }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;