import "../envio.just"

# Run `just --evaluate ENVIO_HASURA_PUBLIC_AGGREGATE` to see the result
export ENVIO_HASURA_PUBLIC_AGGREGATE := ```
    arr=(
        "Action"
        "Activity"
        "Asset"
        "Campaign"
    )
    IFS='&' # Internal Field Separator
    echo "${arr[*]}"
```
export ENVIO_INDEXER_NAME := "airdrops"
export INDEXER_NAME := "airdrops"

# Show available commands
default:
    @just --list
