import "../indexer.just"

# Run `just --evaluate ENVIO_HASURA_PUBLIC_AGGREGATE` to see the result
export ENVIO_HASURA_PUBLIC_AGGREGATE := "Action&Activity&Asset&Campaign&Sponsor&Sponsorship"
export ENVIO_INDEXER_NAME := "airdrops"
export INDEXER_NAME := "airdrops"

# Show available commands
default:
    @just --list
