import type { Types } from "../lib/types";

export const AUTOGEN_COMMENT = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n";
export const PROTOCOLS: Types.Protocol[] = ["airdrops", "flow", "lockup"];
export const VENDORS: Types.Vendor[] = ["envio", "graph"];
