import type { Indexer } from "../src/index.js";

export const AUTOGEN_COMMENT = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n";
export const PROTOCOLS: Indexer.Protocol[] = ["airdrops", "flow", "lockup"];
export const INDEXERS: Indexer.Name[] = [...PROTOCOLS, "analytics", "billing"];
export const VENDORS: Indexer.Vendor[] = ["envio", "graph"];
