import "../envio.just"

export ENVIO_HASURA_PUBLIC_AGGREGATE := ```
    arr=(
        "CryptoFeesDaily"
        "FeeCollection"
        "FeeCollectionDaily"
        "FeeTransaction"
        "FiatFeesDaily"
        "User"
        "UsersActiveMonthly"
        "UserTransaction"
    )
    IFS='&' # Internal Field Separator
    echo "${arr[*]}"
```
export ENVIO_INDEXER_NAME := "analytics"
export INDEXER_NAME := "analytics"

# Show available commands
default:
    @just --list
