JUST_DIR := justfile_dir()

# Show available commands
default:
    @just --list

# Generate all bindings
codegen: codegen-erc20 codegen-prb-proxy

# Generate the ERC-20 bindings
codegen-erc20:
    @just --quiet _codegen erc20 manifest-erc20.yaml

# Generate the PRBProxy bindings
codegen-prb-proxy:
    @just --quiet _codegen prb-proxy manifest-prb-proxy.yaml

[private, script("sh")]
_codegen output_dir manifest:
    rm -rf {{ output_dir }}
    pnpm --dir "{{ JUST_DIR }}/../../.." exec graph codegen \
        --output-dir {{ JUST_DIR }}/{{ output_dir }} \
        {{ JUST_DIR }}/{{ manifest }}
