import "../envio.just"

# Run `just --evaluate ENVIO_HASURA_PUBLIC_AGGREGATE` to see the result
export ENVIO_HASURA_PUBLIC_AGGREGATE := ```
    arr=(
        "User"
        "Action"
    )
    IFS='&' # Internal Field Separator
    echo "${arr[*]}"
```
export ENVIO_INDEXER_NAME := "billing"
export INDEXER_NAME := "billing"

# Show available commands
default:
    @just --list
