# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: sablier-flow
unordered_multichain_mode: true
rollback_on_reorg: false
field_selection:
  transaction_fields:
    - "from"
    - "to"
    - "hash"
    - "transactionIndex"
    - "value"
contracts:
  - name: FlowV10
    handler: src/mappings/index.ts
    events:
      - event: AdjustFlowStream(uint256 indexed streamId, uint256 totalDebt, uint128 oldRatePerSecond, uint128 newRatePerSecond)
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CreateFlowStream(uint256 streamId, address indexed sender, address indexed recipient, uint128 ratePerSecond, address indexed token,
          bool transferable)
      - event: DepositFlowStream(uint256 indexed streamId, address indexed funder, uint128 amount)
      - event: PauseFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint256 totalDebt)
      - event: RefundFromFlowStream(uint256 indexed streamId, address indexed sender, uint128 amount)
      - event: RestartFlowStream(uint256 indexed streamId, address indexed sender, uint128 ratePerSecond)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event: 
          VoidFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, address caller, uint256 newTotalDebt,
          uint256 writtenOffDebt)
      - event: 
          WithdrawFromFlowStream( uint256 indexed streamId, address indexed to, address indexed token, address caller, uint128 withdrawAmount,
          uint128 protocolFeeAmount)
  - name: FlowV11
    handler: src/mappings/index.ts
    events:
      - event: AdjustFlowStream(uint256 indexed streamId, uint256 totalDebt, uint128 oldRatePerSecond, uint128 newRatePerSecond)
      - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event:
          CreateFlowStream(uint256 streamId, address indexed sender, address indexed recipient, uint128 ratePerSecond, address indexed token,
          bool transferable)
      - event: DepositFlowStream(uint256 indexed streamId, address indexed funder, uint128 amount)
      - event: PauseFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, uint256 totalDebt)
      - event: RefundFromFlowStream(uint256 indexed streamId, address indexed sender, uint128 amount)
      - event: RestartFlowStream(uint256 indexed streamId, address indexed sender, uint128 ratePerSecond)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
      - event: TransferAdmin(address indexed oldAdmin, address indexed newAdmin)
      - event: 
          VoidFlowStream(uint256 indexed streamId, address indexed sender, address indexed recipient, address caller, uint256 newTotalDebt,
          uint256 writtenOffDebt)
      - event: 
          WithdrawFromFlowStream( uint256 indexed streamId, address indexed to, address indexed token, address caller, uint128 withdrawAmount,
          uint128 protocolFeeAmount)
networks:
  - id: 42161
    start_block: 161026550
    contracts:
      - name: FlowV10
        address:
          - 0x18a12a7035aa56240bcd236bc019aa245dcc015a
      - name: FlowV11
        address:
          - 0x87cf87ec5de33deb4a88787065373563ba85ee72
  - id: 43114
    start_block: 41023950
    contracts:
      - name: FlowV10
        address:
          - 0x8c172e42c06302e3cfe555dc4d6b71a756ee186b
      - name: FlowV11
        address:
          - 0xac7cb985d4022a5ebd4a385374ac3d3b487b3c63
  - id: 8453
    start_block: 8026890
    contracts:
      - name: FlowV10
        address:
          - 0x1a9adc0e2114c8407cc31669baafeee031d15dd2
      - name: FlowV11
        address:
          - 0x6fe93c7f6cd1dc394e71591e3c42715be7180a6a
  - id: 84532
    start_block: 12641000
    contracts:
      - name: FlowV10
        address:
          - 0xd5f78708d83ac2bc8734a8cdf2d112c1bb3b62a2
      - name: FlowV11
        address:
          - 0xfb6b72a5988a7701a9090c56936269241693a9cc
  - id: 56
    start_block: 34438430
    contracts:
      - name: FlowV10
        address:
          - 0xfce01f79247cf450062545e7155d7bd568551d0e
      - name: FlowV11
        address:
          - 0x4c4610af3f3861ec99b6f6f8066c03e4c3a0e023
  - id: 88888
    start_block: 19125000
    hypersync_config:
      url: https://chiliz.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0x9efc8663cab0e2d97ad17c9fbfc8392445517e94
      - name: FlowV11
        address:
          - 0x28eab88ee8a951f78e1028557d0c3fd97af61a33
  - id: 100
    start_block: 31491790
    contracts:
      - name: FlowV10
        address:
          - 0x5515f774a4db42820802333ba575f68a6e85bd13
      - name: FlowV11
        address:
          - 0x34bc0c2bf1f2da51c65cd821ba4133afcacdb8f5
  - id: 59144
    start_block: 7728000
    contracts:
      - name: FlowV10
        address:
          - 0x949bfa08f1632432a2656a9db17ca34d54da8296
      - name: FlowV11
        address:
          - 0xefc6e4c7dc5faa0cfbfebb5e04ea7cd47f64012f
  - id: 1
    start_block: 17615650
    contracts:
      - name: FlowV10
        address:
          - 0x2d9221a63e12aa796619cb381ec4a71b201281f5
      - name: FlowV11
        address:
          - 0x3df2aaede81d2f6b261f79047517713b8e844e04
  - id: 34443
    start_block: 11343000
    hypersync_config:
      url: https://mode.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0x75970dde488431fc4961494569def3269f20d6b3
      - name: FlowV11
        address:
          - 0xc968e8eefe19bd6de8868df40d9740be127a172a
  - id: 2818
    start_block: 45000
    hypersync_config:
      url: https://morph.hypersync.xyz/
    contracts:
      - name: FlowV10
        address:
          - 0xfe6972d0ae797fae343e5a58d0c7d8513937f092
      - name: FlowV11
        address:
          - 0xf31c8e7d9a0bd310a9d5fb317ba67bb1f0101c6d
  - id: 10
    start_block: 113621900
    contracts:
      - name: FlowV10
        address:
          - 0x906356e4e6410ea0a97dbc5b071cf394ab0dcd69
      - name: FlowV11
        address:
          - 0xc5612fea2d370127ac67048115bd6b1df7b7f7c0
  - id: 137
    start_block: 51245830
    contracts:
      - name: FlowV10
        address:
          - 0xcf2d812d5aad4e6fec3b05850ff056b21159d496
      - name: FlowV11
        address:
          - 0x3e5c4130ea7cfbd364fa5f170289d697865ca94b
  - id: 11155111
    start_block: 4904890
    contracts:
      - name: FlowV10
        address:
          - 0x5ae8c13f6ae094887322012425b34b0919097d8a
      - name: FlowV11
        address:
          - 0x93fe8f86e881a23e5a2feb4b160514fd332576a6
  - id: 534352
    start_block: 1675330
    contracts:
      - name: FlowV10
        address:
          - 0x66826f53bffeaab71adc7fe1a77e86f8268848d8
      - name: FlowV11
        address:
          - 0xc4f104ce12cb12484ff67cf0c4bd0561f0014ec2
  - id: 50104
    start_block: 11290000
    hypersync_config:
      url: https://sophon.hypersync.xyz
    contracts:
      - name: FlowV11
        address:
          - 0x20c9a3e27322fc2b21ced430d1b2e12d90804db6
  - id: 5330
    start_block: 2896400
    hypersync_config:
      url: https://superseed.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0x4f5f9b3fb57bba43aaf90e3f71d8f8f384e88e20
      - name: FlowV11
        address:
          - 0x40e75bb2f2aa3507d3a332872829c71be19ef623
  - id: 5845
    start_block: 2516000
    hypersync_config:
      url: https://tangle.hypersync.xyz
    contracts:
      - name: FlowV10
        address:
          - 0xcff4a803b0bf55dd1be38fb96088478f3d2eecf2
      - name: FlowV11
        address:
          - 0xcb099efc90e88690e287259410b9ae63e1658cc6
  - id: 324
    start_block: 33148900
    contracts:
      - name: FlowV10
        address:
          - 0x015899a075b7c181e357cd0ed000683dbb4f1fce
      - name: FlowV11
        address:
          - 0xe3747379bf7282e0ab5389a63ea053a5256042df
