import "../envio.just"

export ENVIO_HASURA_PUBLIC_AGGREGATE := "Action&Asset&Batch&Stream"
export ENVIO_INDEXER_NAME := "lockup"
export INDEXER_NAME := "lockup"

# Show available commands
default:
    @just --list
