import "../envio.just"

# Run `just --evaluate ENVIO_HASURA_PUBLIC_AGGREGATE` to see the result
export ENVIO_HASURA_PUBLIC_AGGREGATE := "Action&Asset&Batch&Sponsor&Sponsorship&Stream"
export ENVIO_INDEXER_NAME := "lockup"
export INDEXER_NAME := "lockup"

# Show available commands
default:
    @just --list
