import type { Indexer } from "../../src/index.js";

export const AUTOGEN_COMMENT = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n";
export const PROTOCOLS = [
  "airdrops",
  "flow",
  "lockup",
] as const satisfies readonly Indexer.Protocol[];
export const TARGETS = [
  "airdrops",
  "analytics",
  "streams",
] as const satisfies readonly Indexer.Target[];
export const TARGET_OPTIONS = [...TARGETS, "all"] as const satisfies readonly (
  | Indexer.Target
  | "all"
)[];
export const INDEXER_KEYS = [
  "airdrops",
  "streams",
] as const satisfies readonly Indexer.IndexerKey[];
export const GRAPH_TARGETS = [
  "airdrops",
  "streams",
] as const satisfies readonly Indexer.GraphTarget[];
export const GRAPH_TARGET_OPTIONS = [...GRAPH_TARGETS, "all"] as const satisfies readonly (
  | Indexer.GraphTarget
  | "all"
)[];
export const VENDORS = ["envio", "graph"] as const satisfies readonly Indexer.Vendor[];
