name: "CI"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: "Install the Node.js dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Install Just"
        uses: "extractions/setup-just@v3"
        with:
          just-version: "1"

      - name: "Check the code"
        run: "just check"

      - name: "Codegen everything"
        run: "just codegen"

      - name: "Build all subgraphs"
        run: "just build-graph"

      - name: "Run the tests"
        run: "just test"

      - name: "Add summary"
        run: | # shell
          echo "## CI result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
