name: Cron Tests

on:
  schedule:
    - cron: "0 4 */4 * *" # at 04:00 UTC every 4th day
  workflow_dispatch:

jobs:
  test:
    env:
      GRAPH_QUERY_KEY: ${{ secrets.GRAPH_QUERY_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up devkit
        uses: sablier-labs/devkit/actions/setup@main

      - name: Generate the indexer bindings
        run: just codegen

      - name: Check the code
        run: just full-check

      - name: Run the tests
        id: tests
        continue-on-error: true
        env:
          TEST_VENDORS: true
        run: just test

      - name: Generate test summary
        if: always()
        run: bun run ./tests/summarize-test-failures.ts >> $GITHUB_STEP_SUMMARY
