name: Cron Tests

on:
  schedule:
    - cron: "0 4 * * *" # at 04:00 UTC every day
  workflow_dispatch:

jobs:
  test:
    env:
      GRAPH_QUERY_KEY: ${{ secrets.GRAPH_QUERY_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Set up devkit
        uses: sablier-labs/devkit/actions/setup@main
        with:
          package-manager: pnpm

      - name: Generate the indexer bindings
        run: just codegen

      - name: Check the code
        run: just full-check

      - name: Run the tests
        env:
          TEST_VENDORS: true
        run: just test

      - name: Add summary
        run: | # shell
          echo "## Cron Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
