name: Verify Envio Build Files

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  verify-envio-build:
    env:
      CI_LOG_MODE: quiet
      CI_LOG_TAIL_LINES: 200
      ENVIO_ENVIRONMENT: development
      ENVIO_ROUTEMESH_API_KEY: ${{ secrets.ENVIO_ROUTEMESH_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up devkit
        uses: sablier-labs/devkit/actions/setup@v1

      - name: Codegen Envio indexers
        run: just ci-run codegen-envio

      # We need this until this gets implemented in Envio: https://github.com/enviodev/hyperindex/issues/575
      - name: Verify Envio build files haven't changed
        run: | # shell
          bash .github/scripts/verify-no-diff.sh \
            "❌ Envio build files are out of sync. Run 'just codegen-envio' locally and commit the changes." \
            "Envio build file diff" \
            envio/airdrops/config.yaml \
            envio/airdrops/airdrops.graphql \
            envio/streams/config.yaml \
            envio/streams/streams.graphql
